---
- name: repo | install basic packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates

- name: repo | /etc/apt/trusted.gpg.d/nodesoure.asc
  ansible.builtin.get_url:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    dest: /etc/apt/trusted.gpg.d/nodesoure.asc
    mode: 0644
  when: not nodejs_repository_debian

- name: repo | /etc/apt/sources.list.d/nodesource.list
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version_short }}.x {{ ansible_distribution_release }} main"
    filename: nodesource
  when: not nodejs_repository_debian

- name: repo | install nodejs
  ansible.builtin.apt:
    name: nodejs={{ nodejs_version_short }}*
    force: "{{ nodejs_force_install }}"
