---
- name: Repo | get node apt key
  ansible.builtin.get_url:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    dest: /usr/share/keyrings/nodesource.gpg.key
    mode: "0644"

- name: "Repo | generate gpg keys from apt key"
  ansible.builtin.command:
    cmd: "gpg --dearmor /usr/share/keyrings/nodesource.gpg.key"
    creates: "/usr/share/keyrings/nodesource.gpg.key.gpg"
    chdir: "/usr/share/keyrings"
  register: _nodejs_generate_gpg_key
  changed_when: _nodejs_generate_gpg_key.rc != 0

- name: Repo | create node repository file
  ansible.builtin.copy:
    content: "{{ _nodejs_repository_file_content }}"
    dest: "/etc/apt/sources.list.d/node_{{ _nodejs_version_short }}.x.sources"
    mode: "0755"

- name: Repo | install finally nodejs
  ansible.builtin.apt:
    name: nodejs={{ _nodejs_version_short }}*
    update_cache: true
    force: "{{ nodejs_force_install }}"
