---
# https://github.com/nodesource/distributions/issues/33#issuecomment-169345680
- name: Deb | get version matching nodejs_version
  ansible.builtin.set_fact:
    _nodejs_deb_list: "{{ lookup('url', 'https://deb.nodesource.com/node_' ~ _nodejs_version_short ~ '.x/dists/nodistro/main/binary-' ~ nodejs_hardware_architecture ~ '/Packages', split_lines=False) | regex_findall('Filename: .*' ~ nodejs_version ~ '.*') }}"  # noqa 204

- name: Deb | fail if no version match
  ansible.builtin.fail:
    msg: |-
      No version match your `nodejs_version` variable.
  when: not _nodejs_deb_list

- name: Deb | fail if multiple version match
  ansible.builtin.fail:
    msg: >-
      Multiple version match your `nodejs_version` variable.
      Select one from:
      [{%- for nodejs_deb_ in _nodejs_deb_list -%}
      {{ nodejs_deb_[7:] | replace('_amd64.deb', '') }}{% if not loop.last %}, {% endif -%}
      {% endfor -%}
      ]
  when: _nodejs_deb_list | length > 1

- name: Deb | /var/cache/ansible-role-nodejs/
  ansible.builtin.file:
    path: /var/cache/ansible-role-nodejs
    state: directory
    mode: 0755

- name: Set node file path to download
  ansible.builtin.set_fact:
    _nodejs_file_downloading_path: "{{ _nodejs_deb_list[0] | split(':') | last | replace(' ', '') }}"
    _nodejs_file_deb_name: "{{ _nodejs_deb_list[0] | split(':') | last | replace(' ', '') | split('/') | last }}"

- name: Deb | download /var/cache/ansible-role-nodejs/node_…deb
  ansible.builtin.get_url:
    url: "https://deb.nodesource.com/node_{{ _nodejs_version_short }}.x/{{ _nodejs_file_downloading_path }}"
    dest: /var/cache/ansible-role-nodejs/{{ _nodejs_file_deb_name }}
    mode: 0644
  when: nodejs_proxy_settings_http_proxy is not defined and nodejs_proxy_settings_https_proxy is not defined

- name: Deb | download /var/cache/ansible-role-nodejs/node_…deb
  ansible.builtin.get_url:
    url: "https://deb.nodesource.com/node_{{ _nodejs_version_short }}.x/{{ _nodejs_file_downloading_path }}"
    dest: /var/cache/ansible-role-nodejs/{{ _nodejs_file_deb_name }}
    use_proxy: true
    mode: 0644
  environment:
    http_proxy: "{{ nodejs_proxy_settings_http_proxy | default('') }}"
    https_proxy: "{{ nodejs_proxy_settings_https_proxy | default('') }}"
  when: nodejs_proxy_settings_http_proxy is defined or nodejs_proxy_settings_https_proxy is defined

- name: Deb | install nodejs
  ansible.builtin.apt:
    deb: /var/cache/ansible-role-nodejs/{{ _nodejs_file_deb_name }}
    force: "{{ nodejs_force_install }}"
