---
- name: Converge
  hosts: all
  vars:
    nodejs_version: "16.17.1"
    nodejs_npm:
      coffeescript: {}
      chance:
        version: "1.1.3"
      enzyme:
        state: absent
  roles:
    - role: claranet.nodejs
