---
- name: Converge
  hosts: all
  vars:
    nodejs_uses_debian_repository: true
    nodejs_version: "16"
    nodejs_npm:
      coffeescript: {}
      chance:
        version: "1.1.3"
      enzyme:
        state: absent
  roles:
    - role: claranet.nodejs
