---
- name: Converge
  hosts: all
  vars:
    nodejs_proxy_settings_http_proxy: "https://monproxy:3128"
    nodejs_version: "16.17.1-deb-1nodesource1"
    nodejs_npm:
      coffeescript: {}
      chance:
        version: "1.1.3"
      enzyme:
        state: absent
  roles:
    - role: claranet.nodejs
